version: '3'
services:
  unbound:
    image: "techblog/unbound-dns"
    container_name: unbound_dns
    hostname: "unbound"
    restart: unless-stopped
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    volumes:
      - ./custom_unbound.sh:/unbound.sh:ro
      - ./root.hints:/opt/unbound/etc/unbound/var/root.hints:ro
